name: R CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2'  # Specify the R version you want to use

    - name: Install R packages
      run: |
        Rscript install_packages.R

    - name: Run R script
      run: |
        Rscript new.R  # Ensure this matches your script name
